spring:
  application:
    name: spring-cloud-producer
server:
  port: 9001

#\u4F7F\u7528eureka,\u53E6\u5916\u9700\u8981\u4E00\u4E2A\u5E94\u7528\u4F5C\u4E3A\u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    #\u662F\u5426\u6CE8\u518C\u670D\u52A1
    #register-with-eureka: false


#\u4F7F\u7528consul
#spring.cloud.consul.host=127.0.0.1
#spring.cloud.consul.port=8500
#spring.cloud.consul.discovery.register=true
#spring.cloud.consul.discovery.service-name= ${spring.application.name}
